query AllAnunciosByTag ($slug: Mixed!){
    anuncios(
        orderBy: [
            { column: CREATED_AT, order: DESC }
            { column: ANUNCIO_FAVORITO, order: DESC }
        ],
        hasTags:{ column: SLUG, operator: EQ, value: $slug}
    ) {
        id
        anuncio_titulo
        anuncio_local
        anuncio_link
        anuncio_empresa
        anuncio_logo
        anuncio_marcado
        anuncio_favorito
        tags {
            titulo
            slug
            }
        }
}